baseURL: https://ledeniz.github.io/blog/
languageCode: en-us
title: thoughts of a deer
theme: smol

params:
  author: Deniz Erdogan
  subtitle: a blog is a blog is a blog is a blog
  dateFmt: 02.01.2006
